// Centralized User-Facing Copy
export const STRINGS = {
  appName: 'PartyTime',
  login: {
    title: 'Welcome!',
    subtitle: 'Scan the QR code and enter the party passcode to join',
    passcodeLabel: 'Passcode',
    passcodePlaceholder: 'Passcode',
    buttonSubmit: 'Submit',
    buttonSubmitEntering: 'Entering...',
    errorInvalid: 'Oops! That passcode doesn\'t match. Ask the host!'
  },
  onboarding: {
    title: 'Let\'s get set up!',
    subtitle: 'Enter your name and choose your table/team to join the party!',
    nameLabel: 'Name',
    namePlaceholder: 'Name',
    nameSelectLabel: 'Select Your Name',
    nameSelectPlaceholder: '-- Choose your name --',
    nameSelectCustom: 'None of these (Enter my name manually)',
    customNameLabel: 'Enter Your Name',
    teamLabel: 'Select Your Table / Team',
    buttonSubmit: 'Ready!',
    buttonSubmitEntering: 'Entering Party...',
    errorNameRequired: 'Name is required.',
    errorSubmitFailed: 'Failed to create profile. Please try again.'
  },
  dashboard: {
    welcome: 'Hey, {name}!',
    pointsTitle: 'Your Points',
    rankTitle: 'Leaderboard Rank',
    historyTitle: 'Points History',
    noHistory: 'No points earned yet. Go complete some side quests!',
    rankDisplay: '#{rank} of {total}',
    guestsSub: 'of {total} guests',
    guestTag: 'Guest'
  },
  welcomeTab: {
    cardTitle: 'Welcome to the Party!',
    cardBody: 'Welcome, {name}! We are so glad you are here. Complete challenges to earn points, send points to friends, and get ready for Jeopardy!'
  },
  leaderboard: {
    title: 'Leaderboard',
    subtitle: 'Score points to climb the ladder!',
    noPlayers: 'Waiting for guests to join...',
    youSelfTag: 'You',
    pointsUnit: 'pts'
  },
  goals: {
    title: 'Side Quests',
    subtitle: 'Complete these challenges during the party to earn points. The winners will be audited at the end, so tell the truth!',
    claimButton: 'Done!',
    claimButtonClaiming: 'Claiming...',
    pendingStatus: 'Awaiting Host Approval...',
    completedStatus: 'Completed (+{points} pts)',
    noGoals: 'No side quests available yet.',
    claimFailed: 'Could not submit claim. Please try again.',
    popupTitle: 'Important Guidelines',
    popupBody: 'Please read the instructions carefully. Complete the side quests during the party and claim your points. Be honest and fair!',
    popupButton: 'I Acknowledge & Proceed'
  },
  donate: {
    title: 'Donate Points',
    subtitle: 'Feeling generous? Transfer some of your hard-earned points to another guest!',
    recipientLabel: 'Send to:',
    recipientPlaceholder: 'Select a guest...',
    amountLabel: 'Amount (points)',
    amountPlaceholder: 'e.g. 10',
    buttonSubmit: 'Send Points',
    buttonSubmitSending: 'Sending Points...',
    successMsg: 'Successfully sent {amount} points to {name}!',
    errorSelf: 'You cannot send points to yourself.',
    errorInsufficient: 'Insufficient points balance.',
    errorAmount: 'Please enter a valid positive amount.',
    errorNoRecipient: 'Please select a recipient.',
    donationFailed: 'Donation failed. Please try again.'
  },
  tv: {
    title: 'LEADERBOARD',
    joinText: 'JOIN THE PARTY!',
    scanQr: 'Scan the QR code to sign up, see your rank, and send points!',
    rankHeader: 'RANK',
    playerHeader: 'PLAYER',
    scoreHeader: 'SCORE',
    cluePoints: '{points} Points',
    buzzersOpen: 'BUZZERS OPEN',
    waitingForBuzz: 'Waiting for players to buzz in...',
    playerBuzzed: '{name} BUZZED IN!',
    correctBtn: 'Correct (+{points})',
    incorrectBtn: 'Incorrect ({points})',
    skipBtn: 'Skip / Time\'s Up',
    jeopardyWelcome: 'Welcome to Jeopardy!',
    noCategories: 'No Jeopardy categories are configured yet.',
    adminInstructions: 'Go to the Admin Dashboard (/admin), open the Jeopardy Manager tab, and add categories with questions to populate this board!',
    backToLeaderboard: 'Back to Leaderboard',
    deductToggle: 'Deduct points on wrong answers',
    endGame: 'End Game',
    scores: 'SCORES',
    jeopardyMode: 'JEOPARDY',
    
    // New Screens
    welcomeTitle: 'WELCOME TO THE PARTY!',
    welcomeSubtitle: 'We are so glad you are here! Scan the QR code or visit the link to join the leaderboard, view active side quests, and play Jeopardy!',
    welcomeBtn: '👋 Welcome Screen',
    jeopardyBtn: '🎮 Start Jeopardy',
    finaleBtn: '🏆 Finale Screen',
    finaleTitle: 'PARTY FINALE',
    finaleWinnerTitle: '🏆 GRAND CHAMPION 🏆',
    finaleWinnerSubtitle: 'Congratulations to our top performer!',
    finaleStatsTitle: 'PARTY STATISTICS',
    finaleTotalPoints: 'Total Points Scored',
    finaleAvgPoints: 'Average Points / Player',
    finaleTotalPlayers: 'Total Players',
    finaleTopTeam: 'Top Performing Table',
    goodbyeTitle: 'THANKS FOR COMING!',
    goodbyeSubtitle: 'Thank you for celebrating with us tonight! We hope you had a wonderful time. Have a safe journey home!',
    goodbyeWrapUpBtn: '👋 Wrap Up & Say Goodbye'
  },
  admin: {
    gateTitle: 'Host Center',
    gateSubtitle: 'Hello Audrey',
    gatePlaceholder: 'Passcode',
    gateButton: 'Submit',
    gateError: 'Invalid Admin Passcode.',
    headerTitle: 'Lisa & Audrey\'s Grad Party!',
    headerLock: 'Lock Dashboard',
    queueTitle: 'Approval Queue ({count} pending)',
    queueEmpty: 'No pending side quest approvals.',
    queueApproveBtn: 'Approve',
    builderTitle: 'Side Quest Template Builder',
    builderTitlePlaceholder: 'Side Quest Title',
    builderDescPlaceholder: 'Description',
    builderPointsPlaceholder: 'Points Reward',
    builderAddBtn: 'Add Side Quest',
    builderError: 'Title and Points are required.',
    builderErrorFailed: 'Failed to create side quest template.',
    templatesTitle: 'Current Templates',
    playersTitle: 'Player List & Adjustments',
    playersEmpty: 'No players registered yet.',
    adjustCustomPointsPlaceholder: 'Amt (+/-)',
    adjustCustomDescPlaceholder: 'Reason',
    adjustCustomApplyBtn: 'Apply',
    adjustErrorAmount: 'Please enter a valid number.',
    adjustErrorFailed: 'Failed to adjust points: ',
    tabMain: 'Main Panel',
    tabJeopardy: 'Jeopardy Manager',
    jeopardyConfiguredTitle: 'Configured Categories ({count})',
    jeopardyEmpty: 'No Jeopardy categories configured yet.',
    jeopardyDeleteConfirm: 'Are you sure you want to delete the category "{name}"?',
    jeopardyCreateTitle: 'Create New Jeopardy Category',
    jeopardyCatNameLabel: 'Category Name',
    jeopardyCatNamePlaceholder: 'e.g. Science & Nature, Pop Culture',
    jeopardyQuestionPlaceholder: 'Clue Question',
    jeopardyAnswerPlaceholder: 'Clue Answer',
    jeopardySaveBtn: 'Save Category'
  },
  jeopardyBuzzer: {
    buzz: 'TAP TO BUZZ IN!',
    buzzed: 'YOU GOT IT! ANSWER OUT LOUD!',
    tapToBuzz: '',
    ready: '',
    successMsg: '',
    locked: 'Locked :(',
    incorrectLocked: 'Incorrect answer — no more buzzing for you this round.',
    someoneBuzzedFirst: '{name} buzzed first!',
    buzzerLocked: 'Buzzer is currently locked.',
    jeopardyBoardTitle: 'JEOPARDY BOARD',
    yourPoints: 'YOUR POINTS',
    currentTeam: 'CURRENT TEAM',
    waitingBtn: 'WAITING...',
    waitingStatus: 'Come back when it\'s time to play Jeopardy!'
  }
};
